### ISSUE TITLE
Add SASS Support

### ISSUE THREAD

**Issue by shafygunawan** [pamekasancode/Starbase#8]
Saat ini Starbase hanya mendukung css murni. Namun, dengan seiring berkembangnya kompleksitas styling pada suatu proyek, saya harap Starbase dapat mempertimbangkan untuk menambahkan dukungan terhadap SASS untuk manajemen variabel, mixins, dan lain-lain yang lebih baik.

Terima kasih:)

**Comment by AlvinSetyaPranata** [comment]
Terima kasih atas feedback-nya saat ini Starbase masih dalam proses testing ke framework nodeJS yang dimana diharapkan dapat mendukung dengan library css, bundler, dan lainnya stay tuned ^-^p
